USE gimnasio_force_tech;

-- Habilitar el programador de eventos en MySQL
SET GLOBAL event_scheduler = ON;

DELIMITER //

CREATE EVENT IF NOT EXISTS ev_resumen_diario_socios
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP
DO
BEGIN
    INSERT INTO REPORTE_DIARIO_ENTRENADORES (Fecha, ENTRENADOR_ID, Total_Socios)
    SELECT CURDATE(), ENTRENADOR_ID, COUNT(*)
    FROM SOCIO_PLAN_ENTRENAMIENTO
    GROUP BY ENTRENADOR_ID;
END //

DELIMITER ;