CREATE DATABASE IF NOT EXISTS gimnasio_force_tech;
USE gimnasio_force_tech;

-- 1. Catálogo de Ciudades
CREATE TABLE CIUDADES (
    CIUDAD_ID VARCHAR(5) PRIMARY KEY,
    Nombre_Ciudad VARCHAR(50) NOT NULL
);

-- 2. Catálogo de Sedes
CREATE TABLE SEDES (
    SEDE_ID VARCHAR(5) PRIMARY KEY,
    Nombre_Sede VARCHAR(50) NOT NULL,
    Ciudad_Id VARCHAR(5),
    FOREIGN KEY (Ciudad_Id) REFERENCES CIUDADES(CIUDAD_ID)
);

-- 3. Catálogo de Planes de Entrenamiento
CREATE TABLE PLANES_ENTRENAMIENTO (
    PLAN_ENTRENAMIENTO_ID VARCHAR(5) PRIMARY KEY,
    Plan_Entrenamiento VARCHAR(50) NOT NULL
);

-- 4. Catálogo de Especialidades de Entrenadores
CREATE TABLE ESPECIALIDADES_ENTRENADORES (
    ESPECIALIDAD_ID VARCHAR(5) PRIMARY KEY,
    NOMBRE_ESPECIALIDAD VARCHAR(50) NOT NULL
);

-- 5. Tabla de Entrenadores
CREATE TABLE ENTRENADORES (
    ENTRENADOR_ID VARCHAR(5) PRIMARY KEY,
    Nombres VARCHAR(50) NOT NULL,
    Apellidos VARCHAR(50) NOT NULL,
    ESPECIALIDAD_ID VARCHAR(5),
    SEDE_ID VARCHAR(5),
    Cupo_Maximo INT DEFAULT 10,
    FOREIGN KEY (ESPECIALIDAD_ID) REFERENCES ESPECIALIDADES_ENTRENADORES(ESPECIALIDAD_ID),
    FOREIGN KEY (SEDE_ID) REFERENCES SEDES(SEDE_ID)
);

-- 6. Tabla de Socios
CREATE TABLE SOCIOS (
    Socio_ID INT PRIMARY KEY,
    Nombres VARCHAR(50) NOT NULL,
    Apellidos VARCHAR(50) NOT NULL,
    Telefono VARCHAR(20)
);

-- 7. Tabla Socio Plan Entrenamiento (Relacional en 4FN)
CREATE TABLE SOCIO_PLAN_ENTRENAMIENTO (
    ID_ASIGNACION INT AUTO_INCREMENT PRIMARY KEY,
    Socio_ID INT,
    PLAN_ENTRENAMIENTO_ID VARCHAR(5),
    ENTRENADOR_ID VARCHAR(5),
    SEDE_ID VARCHAR(5),
    Fecha_Asignacion DATE,
    FOREIGN KEY (Socio_ID) REFERENCES SOCIOS(Socio_ID),
    FOREIGN KEY (PLAN_ENTRENAMIENTO_ID) REFERENCES PLANES_ENTRENAMIENTO(PLAN_ENTRENAMIENTO_ID),
    FOREIGN KEY (ENTRENADOR_ID) REFERENCES ENTRENADORES(ENTRENADOR_ID),
    FOREIGN KEY (SEDE_ID) REFERENCES SEDES(SEDE_ID)
);

-- 8. Tabla para Reportes Diarios
CREATE TABLE REPORTE_DIARIO_ENTRENADORES (
    Reporte_ID INT AUTO_INCREMENT PRIMARY KEY,
    Fecha DATE,
    ENTRENADOR_ID VARCHAR(5),
    Total_Socios INT,
    FOREIGN KEY (ENTRENADOR_ID) REFERENCES ENTRENADORES(ENTRENADOR_ID)
);